# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('direction', models.CharField(choices=[('DISBURSEMENT', 'Disbursement (Payout / Send)'), ('COLLECTION', 'Collection (Payment Received)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('channel', models.CharField(max_length=30)),
                ('counterparty_name', models.CharField(max_length=255)),
                ('counterparty_identifier', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Rail Clearing'), ('SUCCESS', 'Completed / Settled'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='SUCCESS', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
