# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('target_type', models.CharField(choices=[('PHONE_MOMO', 'Mobile Money Subscriber'), ('BANK_ACCOUNT', 'Bank Account / IBAN'), ('BUSINESS_RCCM', 'Commercial Registry (RCCM)'), ('TAX_TIN', 'Tax Identification Number')], max_length=30)),
                ('target_identifier', models.CharField(max_length=150)),
                ('expected_name', models.CharField(blank=True, max_length=255)),
                ('registered_name', models.CharField(max_length=255)),
                ('match_status', models.CharField(choices=[('EXACT_MATCH', 'Exact Name Match'), ('PARTIAL_MATCH', 'Acceptable Partial Match'), ('MISMATCH', 'Severe Name Mismatch / Warning'), ('NOT_FOUND', 'Target Not Found')], max_length=30)),
                ('confidence_score', models.FloatField(default=100.0)),
                ('carrier_or_bank', models.CharField(blank=True, max_length=100)),
                ('is_safe_to_pay', models.BooleanField(default=True)),
                ('raw_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobira_verification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('IN_PROGRESS', 'In Progress'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=30)),
                ('verification_type', models.CharField(default='FULL_KYB', max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('documents_submitted', models.JSONField(blank=True, default=list)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='businesses.business')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mobira_business_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='mobira_busi_busines_0dbe7f_idx')],
            },
        ),
    ]
