# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('account_identifier', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Dual Approval (Checker)'), ('PROCESSING', 'Processing on Telecom/Bank Rail'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed on Rail'), ('REJECTED', 'Rejected by Checker')], default='PROCESSING', max_length=30)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('requires_checker', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_preflight_verified', models.BooleanField(default=False)),
                ('preflight_confidence', models.FloatField(default=0.0)),
                ('provider_name', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
