# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(max_length=30)),
                ('account_identifier', models.CharField(max_length=100)),
                ('category', models.CharField(default='Supplier', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_name', models.CharField(blank=True, max_length=255)),
                ('verification_confidence', models.FloatField(default=0.0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('total_disbursed_xaf', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('payout_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_recipients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recipients.recipient',),
        ),
    ]
