# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Employees', 'Employees'), ('Suppliers', 'Suppliers'), ('Contractors', 'Contractors'), ('Vendors', 'Vendors'), ('Other beneficiaries', 'Other beneficiaries')], default='Employees', max_length=50)),
                ('recipient_count', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='GH₵', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='READY', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_disbursed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobira_payment_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentListRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('provider', models.CharField(default='MTN_MOMO', max_length=50)),
                ('account', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('role_or_item', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=True)),
                ('returned_account_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mobira_payment_list_recipients',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Pre-flight Validated'), ('EXECUTING', 'Executing Batch Dispatches'), ('COMPLETED', 'Batch Completed'), ('PARTIAL_FAILURE', 'Completed with Line Item Errors')], default='VALIDATED', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_count', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('successful_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_batches', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_payment_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('account_identifier', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment_lists.paymentbatch')),
            ],
            options={
                'db_table': 'mobira_payment_batch_items',
            },
        ),
    ]
