# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('payment_lists', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbatchitem',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentlist',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_lists', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='paymentlistrecipient',
            name='payment_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='payment_lists.paymentlist'),
        ),
        migrations.CreateModel(
            name='PaymentListMember',
            fields=[
            ],
            options={
                'verbose_name': 'Payment List Member',
                'verbose_name_plural': 'Payment List Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment_lists.paymentlistrecipient',),
        ),
    ]
