# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('allow_custom_amount', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_data', models.TextField(blank=True)),
                ('total_collected_xaf', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('collections_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_payment_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=64, unique=True)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_phone', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('status', models.CharField(default='SUCCESS', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='businesses.business')),
                ('payment_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='receive.paymentlink')),
            ],
            options={
                'db_table': 'mobira_collections',
                'ordering': ['-created_at'],
            },
        ),
    ]
