# Generated by Django 6.0.6 on 2026-09-04 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('business_id', models.CharField(default='PP-ABC-001', help_text='Public Business Identifier, e.g. PP-ABC-001', max_length=50, unique=True)),
                ('legal_form', models.CharField(default='LTD', max_length=50)),
                ('registration_number', models.CharField(help_text='Official Registry / RCCM Number', max_length=100, unique=True)),
                ('tax_number', models.CharField(help_text='TIN / NIU', max_length=100, unique=True)),
                ('category', models.CharField(default='Technology & Software', help_text='Business Category / Industry', max_length=100)),
                ('sector', models.CharField(default='Technology & Software', max_length=100)),
                ('country', models.CharField(default='Ghana', max_length=50)),
                ('city', models.CharField(default='Accra', max_length=100)),
                ('location', models.CharField(default='Accra, Ghana', help_text='City, Country Location', max_length=150)),
                ('address', models.CharField(default='14 Independence Avenue, Ridge, Accra', max_length=255)),
                ('phone', models.CharField(default='+233 24 123 4567', max_length=30)),
                ('email', models.EmailField(default='info@abctechnologies.com', max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, help_text='Logo asset URL', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='Leading provider of enterprise financial orchestration, cloud infrastructure, and verified B2B identity rails across West and Central Africa.')),
                ('verification_tier', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('BASIC_VERIFIED', 'Basic Verified'), ('VERIFIED_TIER_1', 'Verified Tier 1'), ('GOLD_VERIFIED', 'Gold Verified Business')], default='GOLD_VERIFIED', max_length=30)),
                ('trust_score', models.IntegerField(default=96, help_text='Algorithmic score from 0 to 100')),
                ('is_active', models.BooleanField(default=True)),
                ('daily_payment_limit', models.DecimalField(decimal_places=2, default=15000000.0, max_digits=12)),
                ('primary_momo_number', models.CharField(blank=True, max_length=30)),
                ('primary_bank_account', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
                'db_table': 'mobira_businesses',
                'ordering': ['-trust_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPaymentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_disbursement_limit', models.DecimalField(decimal_places=2, default=15000000.0, max_digits=14)),
                ('single_transaction_limit', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=14)),
                ('maker_checker_threshold', models.DecimalField(decimal_places=2, default=500000.0, max_digits=14)),
                ('requires_dual_approval', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='GHS', max_length=10)),
                ('default_channel', models.CharField(default='MTN_MOMO', max_length=30)),
                ('can_send_payments', models.BooleanField(default=True)),
                ('can_receive_payments', models.BooleanField(default=True)),
                ('can_create_payment_links', models.BooleanField(default=True)),
                ('auto_verify_recipients', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_business_payment_profiles',
            },
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_type', models.CharField(default='MOBILE_MONEY', max_length=30)),
                ('account_name', models.CharField(max_length=255)),
                ('masked_number', models.CharField(help_text='Masked account ID, e.g. •••• 4821', max_length=50)),
                ('status', models.CharField(choices=[('DEMO_CONNECTED', 'Demo Connected'), ('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected')], default='DEMO_CONNECTED', max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=12)),
                ('is_simulated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_connected_accounts',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=30)),
                ('account_name', models.CharField(max_length=255)),
                ('account_identifier', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='businesses.business')),
            ],
            options={
                'db_table': 'mobira_disbursement_accounts',
            },
        ),
    ]
